### ISSUE TITLE
answer-placeholder-1732085440997 is not a valid uuid.

### ISSUE THREAD

**Issue by nowcoder-zhaozhen** [langgenius/dify#10894]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.10.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

<img width="453" alt="1" src="https://github.com/user-attachments/assets/2386e243-187a-425e-aac4-9e16e23b34ec">
Change the Docker Composer deployment to Kubernetes deployment and synchronize the database. Some studios have encountered errors, as shown in the picture. May I ask why this is

### ✔️ Expected Behavior

I hope to convert the dock compose type dify deployed on the server to k8s type deployment and ensure that data is not lost

### ❌ Actual Behavior

After the deployment type conversion, I didn't know what the purpose of weaviate was, so I didn't migrate to k8s. Just copied the PEM under the path/app/app/storage/privkeys/7d 4c33 d7-6bb8-476c a233-b9df 1d348b34 from Docker Compose to the pod of k8s

**Comment by crazywoola** [comment]
This issue has been resolved in our latest version.

**Comment by nowcoder-zhaozhen** [comment]
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";  It has been executed and confirmed successfully, but the error still persists. So I upgraded DIY to the latest version, but DIY API encountered an error: Exception: Query was not successful! Unexpected status code: 422, with response body: {'error': [{'message': 'no graphql provider present, this is most likely because no schema is present. Import a schema first!'}]}.
2024-11-20 09:33:08,893.893 ERROR [Dummy-29] [base_app_generate_response_converter.py:131] - Query was not successful!  Unexpected status code: 422, with response body: {'error': [{'message': 'no graphql provider present, this is most likely because no schema is present. Import a schema first!'}]}.
