### ISSUE TITLE
The plugin has been installing for a long time, but it has appeared in the plugin list, yet it cannot be used normally

### ISSUE THREAD

**Issue by xmccln** [langgenius/dify#14617]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.0.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![Image](https://github.com/user-attachments/assets/fe44a937-8299-495a-8306-05fae21723a5)
The plugin has been installing for a long time, but it has appeared in the plugin list, yet it cannot be used normally
```log
ca01c5-b17f-4b73-8059-7b44fee03f67/management/install/tasks?page=1&page_size=100"
2025/03/01 09:39:54 runtime_lifetime.go:76: [ERROR]init environment failed: failed to install dependencies: signal: killed, output: init process exited due to no activity for 120 seconds, retry in 30s
2025/03/01 09:40:24 runtime_lifetime.go:70: [INFO]init environment for plugin langgenius/agent:0.0.8
2025/03/01 09:40:41
```
I found this error.

### ✔️ Expected Behavior

Do not display plugin installation, or allow me to cancel the installation

### ❌ Actual Behavior

No function to cancel installation, and the plugin has been installed for nearly an hour without any movement

**Comment by xmccln** [comment]
I found that the data in http://xxx/console/api/workspaces/current/plugin/tasks?page=1&page_size=100 contains
```data
{
    "tasks": [
        {
            "id": "98a388a5-12b6-40f1-bdad-a628931f9678",
            "created_at": "2025-03-01T09:47:36.425243Z",
            "updated_at": "2025-03-01T09:51:36.546640Z",
            "status": "success",
            "total_plugins": 1,
            "completed_plugins": 1,
            "plugins": [
                {
                    "plugin_unique_identifier": "langgenius/siliconflow:0.0.7@62b7aa3a2ac0cbf22566f671670305175d0b89cf723a41fb88f103eb413b2962",
                    "plugin_id": "langgenius/siliconflow",
                    "status": "success",
                    "message": "Installed",
                    "icon": "0dbcd12864243bfcd8c0c1898a3e0c37ea553c21a727800b0863a599a9660729.svg",
                    "labels": {
                        "en_US": "SiliconFlow",
                        "zh_Hans": "\u7845\u57fa\u6d41\u52a8",
                        "pt_BR": "SiliconFlow",
                        "ja_JP": "SiliconFlow"
                    }
                }
            ]
        },
        {
            "id": "bde89523-1b74-4b22-88ea-6cb25cb014d3",
            "created_at": "2025-03-01T09:47:10.642710Z",
            "updated_at": "2025-03-01T09:47:10.709329Z",
            "status": "failed",
            "total_plugins": 1,
            "completed_plugins": 0,
            "plugins": [
                {
                    "plugin_unique_identifier": "langgenius/siliconflow:0.0.7@62b7aa3a2ac0cbf22566f671670305175d0b89cf723a41fb88f103eb413b2962",
                    "plugin_id": "langgenius/siliconflow",
                    "status": "failed",
                    "message": "open storage/plugin_packages/langgenius/siliconflow:0.0.7@62b7aa3a2ac0cbf22566f671670305175d0b89cf723a41fb88f103eb413b2962: no such file or directory",
                    "icon": "0dbcd12864243bfcd8c0c1898a3e0c37ea553c21a727800b0863a599a9660729.svg",
                    "labels": {
                        "en_US": "SiliconFlow",
                        "zh_Hans": "\u7845\u57fa\u6d41\u52a8",
                        "pt_BR": "SiliconFlow",
                        "ja_JP": "SiliconFlow"
                    }
                }
            ]
        },
        {
            "id": "f621fba6-92ff-4547-84cc-17fab49045e5",
            "created_at": "2025-03-01T09:47:07.124464Z",
            "updated_at": "2025-03-01T09:47:07.155899Z",
            "status": "failed",
            "total_plugins": 1,
            "completed_plugins": 0,
            "plugins": [
                {
                    "plugin_unique_identifier": "langgenius/siliconflow:0.0.7@62b7aa3a2ac0cbf22566f671670305175d0b89cf723a41fb88f103eb413b2962",
                    "plugin_id": "langgenius/siliconflow",
                    "status": "failed",
                    "message": "open storage/plugin_packages/langgenius/siliconflow:0.0.7@62b7aa3a2ac0cbf22566f671670305175d0b89cf723a41fb88f103eb413b2962: no such file or directory",
                    "icon": "0dbcd12864243bfcd8c0c1898a3e0c37ea553c21a727800b0863a599a9660729.svg",
                    "labels": {
                        "en_US": "SiliconFlow",
                        "zh_Hans": "\u7845\u57fa\u6d41\u52a8",
                        "pt_BR": "SiliconFlow",
                        "ja_JP": "SiliconFlow"
                    }
                }
            ]
        },
        {
            "id": "1683bcec-90fc-4548-ad2b-5e29d4c8c39d",
            "created_at": "2025-03-01T09:42:27.788737Z",
            "updated_at": "2025-03-01T09:42:27.841255Z",
            "status": "failed",
            "total_plugins": 1,
            "completed_plugins": 0,
            "plugins": [
                {
                    "plugin_unique_identifier": "langgenius/siliconflow:0.0.7@62b7aa3a2ac0cbf22566f671670305175d0b89cf723a41fb88f103eb413b2962",
                    "plugin_id": "langgenius/siliconflow",
                    "status": "failed",
                    "message": "open storage/plugin_packages/langgenius/siliconflow:0.0.7@62b7aa3a2ac0cbf22566f671670305175d0b89cf723a41fb88f103eb413b2962: no such file or directory",
                    "icon": "0dbcd12864243bfcd8c0c1898a3e0c37ea553c21a727800b0863a599a9660729.svg",
                    "labels": {
                        "en_US": "SiliconFlow",
                        "zh_Hans": "\u7845\u57fa\u6d41\u52a8",
                        "pt_BR": "SiliconFlow",
                        "ja_JP": "SiliconFlow"
                    }
                }
            ]
        },
        {
            "id": "b54518e6-28c1-4023-a468-63033b38bf53",
            "created_at": "2025-03-01T09:27:41.203325Z",
            "updated_at": "2025-03-01T09:27:41.218756Z",
            "status": "running",
            "total_plugins": 1,
            "completed_plugins": 0,
            "plugins": [
                {
                    "plugin_unique_identifier": "langgenius/siliconflow:0.0.7@62b7aa3a2ac0cbf22566f671670305175d0b89cf723a41fb88f103eb413b2962",
                    "plugin_id": "langgenius/siliconflow",
                    "status": "running",
                    "message": "Installing",
                    "icon": "0dbcd12864243bfcd8c0c1898a3e0c37ea553c21a727800b0863a599a9660729.svg",
                    "labels": {
                        "en_US": "SiliconFlow",
                        "zh_Hans": "\u7845\u57fa\u6d41\u52a8",
                        "pt_BR": "SiliconFlow",
                        "ja_JP": "SiliconFlow"
                    }
                }
            ]
        },
        {
            "id": "93acfcb2-cb61-4d17-b2cf-8d7d3819293b",
            "created_at": "2025-02-27T13:56:12.561188Z",
            "updated_at": "2025-02-27T13:56:12.690348Z",
            "status": "running",
            "total_plugins": 1,
            "completed_plugins": 0,
            "plugins": [
                {
                    "plugin_unique_identifier": "langgenius/siliconflow:0.0.6@c18c51703888e0156ade8b410ad53d8dc8d7bcf6ddcb37d2d0b0492365c992e7",
                    "plugin_id": "langgenius/siliconflow",
                    "status": "running",
                    "message": "Installing",
                    "icon": "0dbcd12864243bfcd8c0c1898a3e0c37ea553c21a727800b0863a599a9660729.svg",
                    "labels": {
                        "en_US": "SiliconFlow",
                        "zh_Hans": "\u7845\u57fa\u6d41\u52a8",
                        "pt_BR": "SiliconFlow",
                        "ja_JP": "SiliconFlow"
                    }
                }
            ]
        }
    ]
}
```
看起来是由于重复提交安装任务导致的，这该如何解决

**Comment by unknown-22** [comment]
I encountered the same issue.
It was solved by setting the `PYTHON_ENV_INIT_TIMEOUT` environment variable.

This has been fixed in the following PR:
https://github.com/langgenius/dify-plugin-daemon/pull/8

Please add the following to your `docker/docker-compose.yaml` file:
```
  plugin_daemon:
    ...
    environment:
      # Use the shared environment variables.
      ...
      PYTHON_ENV_INIT_TIMEOUT: 320
```

**Comment by lm970585581** [comment]
Can plugins modify the mirror source?

**Comment by crazywoola** [comment]
We fixed in https://github.com/langgenius/dify-plugin-daemon/pull/59

```
  plugin_daemon:
    image: langgenius/dify-plugin-daemon:e0672c3c1a6451437e8f4b63b260c8b0863c9c80-local
```

**Comment by jackqdldd** [comment]
> We fixed in [langgenius/dify-plugin-daemon#59](https://github.com/langgenius/dify-plugin-daemon/pull/59)
> 
> ```
>   plugin_daemon:
>     image: langgenius/dify-plugin-daemon:e0672c3c1a6451437e8f4b63b260c8b0863c9c80-local
> ```

Hey ，I used the version mentioned above and it still failed.

![Image](https://github.com/user-attachments/assets/e19074c7-7018-412c-a647-f6ca72bb678a)

**Comment by KzNight** [comment]
https://www.bilibili.com/video/BV1f6R8YbEqG/?spm_id_from=333.788.comment.all.click&vd_source=03d1b4784c326e357d854f6668666d67
试试这个
