### ISSUE TITLE
Dify Mail Plugin Compatibility Issue with QQ SMTP

### ISSUE THREAD

**Issue by youshanmomei** [langgenius/dify#15248]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.0.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

![Image](https://github.com/user-attachments/assets/7739c1aa-1520-4f2d-a676-1a9257dee571)

The mail plugin in Dify is experiencing a parameter exception when attempting to use QQ SMTP for email services. This issue prevents the plugin from functioning correctly with QQ email accounts. The error suggests there might be a mismatch in SMTP parameters or an incompatibility with QQ's specific SMTP requirements. .

### ✔️ Expected Behavior

to ensure proper functionality of the mail plugin with QQ SMTP servers.

### ❌ Actual Behavior

Connection failure

**Comment by crazywoola** [comment]
This should be fixed later.

**Comment by youshanmomei** [comment]
@crazywoola I see that you have closed the issues. Has the repair been completed? But I still can't find the mail plugin in the plugin platform. Do I need to wait for a while?

**Comment by WolfricWang** [comment]
I am facing the same problems. This email plugin can't works. I tried changing the .env configuration, still not work. I even try to use the gmail smtp. And there not much useful information in Logs.

**Comment by crazywoola** [comment]
> I am facing the same problems. This email plugin can't works. I tried changing the .env configuration, still not work. I even try to use the gmail smtp. And there not much useful information in Logs.

I don't think you need to change the `.env` when you are using email plugin.

**Comment by crazywoola** [comment]
> [@crazywoola](https://github.com/crazywoola) I see that you have closed the issues. Has the repair been completed? But I still can't find the mail plugin in the plugin platform. Do I need to wait for a while?

<img width="558" alt="Image" src="https://github.com/user-attachments/assets/72b42479-d1df-48f9-bddc-5d9a61e8ea27" />

**Comment by WolfricWang** [comment]
> > I am facing the same problems. This email plugin can't works. I tried changing the .env configuration, still not work. I even try to use the gmail smtp. And there not much useful information in Logs.
> 
> I don't think you need to change the `.env` when you are using email plugin.

Yes, you are right. But there is still a problem for me to send to multiple recipients. I use a loop to send one by one now.
