### ISSUE TITLE
Knoewledge batch add chunk function is not woking in QA mode and Chunk Settings report error when editing.

### ISSUE THREAD

**Issue by szkane** [langgenius/dify#16619]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:)
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.1.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

> I redeployed a new dify 1.12 docker, and during the process of creating the knowledge base, I found that two features were not working properly, which prevented me from deploying down.
> 我重新部署了一个新的dify 1.12 docker，在创建知识库过程中，发现两个功能工作不正常，导致无法往下部署。

## Bug1:  batch add chunk  function is not workding

STEP1. import empty.txt  file and use  Q&A format, then save.

![Image](https://github.com/user-attachments/assets/76a2fd16-5719-4527-a02c-090762a999a6)

STEP2. Click batch add and there is no response.

![Image](https://github.com/user-attachments/assets/93449f72-716e-4e29-a01d-525e2ce0a670)

0.15.3 version could show a Q&A file upload window.

## Bug2: update Chunk Settings  get error 400,  error code below:

```
{
    "code": "invalid_param",
    "message": "1 validation error for KnowledgeConfig\nretrieval_model.weights.weight_type\n  Field required [type=missing, input_value={'keyword_setting': {'key...ing_provider_name': ''}}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.9/v/missing",
    "status": 400
}
```

### ✔️ Expected Behavior

1. batch add Q&A  file via csv
2. could be update when modify  chunk setting

**Comment by crazywoola** [comment]
See https://github.com/langgenius/dify/issues/16609

Fixed in https://github.com/langgenius/dify/pull/16503

Duplicated 
- https://github.com/langgenius/dify/issues/16592
- https://github.com/langgenius/dify/issues/16591
- https://github.com/langgenius/dify/issues/16589
- https://github.com/langgenius/dify/issues/16411
- https://github.com/langgenius/dify/issues/16142

**Comment by xuegao-tzx** [comment]
Not fixed, still has issues in 1.1.3

<img width="369" alt="Image" src="https://github.com/user-attachments/assets/8fe7372c-a4d8-4d3b-90ec-da412ed2c7cc" />

<img width="495" alt="Image" src="https://github.com/user-attachments/assets/c6aa0460-91dd-46f9-b9d1-890269ffd503" />

**Comment by WTW0313** [comment]
Bug2 should be fixed in version 1.1.3. Bug1 will be fixed soon.

**Comment by szkane** [comment]
@WTW0313 Still not wokring batch add chunk  in  v1.1.3
