### ISSUE TITLE
Dify did not respond. The error message was: core.model_runtime.errors.invoke.InvokeBadRequestError: [models] Bad Request Error, The read operation timed out

### ISSUE THREAD

**Issue by zzzjw666** [langgenius/dify#19438]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:)
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.1.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I checked the dify logs, here is the specific error message:

Exception in thread Thread-235617 (_retriever):
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/app/api/core/rag/retrieval/dataset_retrieval.py", line 620, in _retriever
    documents = RetrievalService.retrieve(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/core/rag/datasource/retrieval_service.py", line 111, in retrieve
    all_documents = data_post_processor.invoke(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/core/rag/data_post_processor/data_post_processor.py", line 37, in invoke
    documents = self.rerank_runner.run(query, documents, score_threshold, top_n, user)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/core/rag/rerank/rerank_model.py", line 48, in run
    rerank_result = self.rerank_model_instance.invoke_rerank(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/core/model_manager.py", line 276, in invoke_rerank
    self._round_robin_invoke(
  File "/app/api/core/model_manager.py", line 370, in _round_robin_invoke
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/core/model_runtime/model_providers/__base/rerank_model.py", line 53, in invoke
    raise self._transform_invoke_error(e)
  File "/app/api/core/model_runtime/model_providers/__base/rerank_model.py", line 40, in invoke
    return plugin_model_manager.invoke_rerank(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/api/core/plugin/manager/model.py", line 359, in invoke_rerank
    for resp in response:
                ^^^^^^^^
  File "/app/api/core/plugin/manager/base.py", line 189, in _request_with_plugin_daemon_response_stream
    self._handle_plugin_daemon_error(error.error_type, error.message)
  File "/app/api/core/plugin/manager/base.py", line 213, in _handle_plugin_daemon_error
    raise InvokeBadRequestError(description=args.get("description"))
core.model_runtime.errors.invoke.InvokeBadRequestError: [models] Bad Request Error, The read operation timed ou

**Comment by crazywoola** [comment]
I suggest you upgrading to v1.3.1. Check the status and logs of plugin_daemon.

**Comment by zzzjw666** [comment]
> I suggest you upgrading to v1.3.1. Check the status and logs of plugin_daemon.

I'm not sure if this problem will occur after the upgrade.

**Comment by crazywoola** [comment]
If it can not be reproduced in latest version , then it should be fixed already.

**Comment by zzzjw666** [comment]
> If it can not be reproduced in latest version , then it should be fixed already.

I upgraded dify to version 1.3.1, but the problem still occurred.
