### ISSUE TITLE
上传插件，dify-plugin-daemon容器报错，

### ISSUE THREAD

**Issue by lizige** [langgenius/dify#20800]
### Self Checks

- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [x] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:)
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.4.1

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

麒麟v10离线部署dify1.4.1，上传离线插件，dify-plugin-daemon容器报错:
init envrironment failed:failded to create  virtual environment:exit status 101,output:
Tokio executor failed was there a panic?:os{code:1,kind:PermissionDenied,message:"Operation not permitted}

**Comment by lizige** [comment]
Thank you very much, this problem has been solved with your solution

**Comment by FlySongSwen** [comment]
> Thank you very much, this problem has been solved with your solution

I got the same error.
I used 'chmod' to change the './volumes/plugin_daemon'
but still pop the same error.

**Comment by FlySongSwen** [comment]
> > Thank you very much, this problem has been solved with your solution
> 
> I got the same error. I used 'chmod' to change the './volumes/plugin_daemon' but still pop the same error.

i solved this adding below configuration
**security_opt:
  - seccomp:unconfined**

but still can't not install plugin.
[Error] init environment fail: failed to install dependencies: exit status 1

the gevent  required CPython 3.12
