### ISSUE TITLE
Use pasted picture link to report errors

### ISSUE THREAD

**Issue by hackerHiJu** [langgenius/dify#25211]
### Self Checks

- [x] I have read the [Contributing Guide](https://github.com/langgenius/dify/blob/main/CONTRIBUTING.md) and [Language Policy](https://github.com/langgenius/dify/issues/1542).
- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report, otherwise it will be closed.
- [x] 【中文用户 & Non English User】请使用英语提交，否则会被关闭 ：）
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.7.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

<img width="446" height="822" alt="Image" src="https://github.com/user-attachments/assets/db11e364-5d33-4969-b53f-3ac6efc0bf1e" />

### ✔️ Expected Behavior

Use pasted picture link to report errors

<img width="403" height="543" alt="Image" src="https://github.com/user-attachments/assets/b3c0d7d2-8a11-4c75-8134-df938317f841" />

<img width="446" height="822" alt="Image" src="https://github.com/user-attachments/assets/b61accf6-3416-41cf-85f1-b92e57c0e57b" />

**Comment by crazywoola** [comment]
Duplicated fixed in 1.8.1

**Comment by hyqf98** [comment]
> Duplicated fixed in 1.8.1

The same problem was reported after the upgrade was completed

<img width="417" height="643" alt="Image" src="https://github.com/user-attachments/assets/214080ad-7935-4a66-a2c4-989229b0176f" />

**Comment by hyqf98** [comment]
> Duplicated fixed in 1.8.1

Hello, I still have this problem after upgrading the latest version
