### ISSUE TITLE
“The status of the uploaded document on the pipeline has always shown as "Queuing".” This issue was claimed to have been resolved, but when pulling the latest branch, the bug still exists.

### ISSUE THREAD

**Issue by Richie666888** [langgenius/dify#27625]
### Self Checks

- [x] I have read the [Contributing Guide](https://github.com/langgenius/dify/blob/main/CONTRIBUTING.md) and [Language Policy](https://github.com/langgenius/dify/issues/1542).
- [x] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [x] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [x] I confirm that I am using English to submit this report, otherwise it will be closed.
- [x] 【中文用户 & Non English User】请使用英语提交，否则会被关闭 ：）
- [x] Please do not modify this template :) and fill in all the required fields.

### Dify version

1.9.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

“The status of the uploaded document on the pipeline has always shown as "Queuing".” This issue was claimed to have been resolved, but when pulling the latest branch, the bug still exists.

### ✔️ Expected Behavior

normal index

### ❌ Actual Behavior

“The status of the uploaded document on the pipeline has always shown as "Queuing".” This issue was claimed to have been resolved, but when pulling the latest branch, the bug still exists.

**Comment by Richie666888** [comment]
@crazywoola You can reproduce this bug by reverting from version 1.8.1 to version 1.9.2.Deploy using Docker.

**Comment by crazywoola** [comment]
I think this should be resolved in v1.9.2. This is a known issue in v1.8.1

**Comment by Richie666888** [comment]
> I think this should be resolved in v1.9.2. This is a known issue in v1.8.1

I completely restarted the process of pulling version 1.9.2 using Docker Desktop, but the bug still persists. Could you please tell me your re-enactment process?

**Comment by leike0813** [comment]
Same issue +1, 1.9.2, docker deployed.
Queue forever after the knowledge pipeline has been publishd,
but works fine in test runs.

**Comment by h1xy** [comment]
exactly same issue as @leike0813

**Comment by Richie666888** [comment]
Which esteemed person could possibly solve this problem?

**Comment by leike0813** [comment]
> Which esteemed person could possibly solve this problem?

Currently, my issue only occurs in the knowledge workflow that requires automatic uploading and parsing of PDFs using the MinerU plugin. (I haven't tested whether the built-in parser works correctly.)

As a temporary solution, I made a simple [MinerU Batch Parsing Client](https://github.com/leike0813/MinerU-Client).

Directly uploading the parsed .md files works properly.

P.S. This client has the official API hard-coded; if you want to use your own API, you can modify the source code.)
