### ISSUE TITLE
a client-side exception has occurred (see the browser console for more information),,,,,

### ISSUE THREAD

**Issue by zhangxiaolin718** [langgenius/dify#6603]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.11

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

When I send a message, the model replies and this interface appears

### ✔️ Expected Behavior

Continue the conversation

<img width="413" alt="error" src="https://github.com/user-attachments/assets/4598715d-5b0c-4b71-91e8-d7d7db5b1719">

### ❌ Actual Behavior

Application error: a client-side exception has occurred (see the browser console for more information)
<img width="413" alt="error" src="https://github.com/user-attachments/assets/13a7ef37-327d-40ee-85de-80b4c885594b">

**Comment by crazywoola** [comment]
Please upgrade to latest version, we have fixed this error in later versions.

**Comment by darkmirrors** [comment]
> Please upgrade to latest version, we have fixed this error in later versions.

no, i have upgreded to the version 0.6.16 , the problem is still happen

**Comment by darkmirrors** [comment]
@crazywoola  the problem still happen in 0.6.16
