### ISSUE TITLE
tool calling errro

### ISSUE THREAD

**Issue by fwasdfw** [langgenius/dify#6736]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.14 or 0.6.15

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

in an agent apps , i use tongyi model with a tool searxng, but invoke  will error by web: 
[tongyi] Server Unavailable Error, Failed to invoke model qwen-turbo, status code: 500, message: messages with role "tool" must be a response to a preceeding message with "tool_calls".

### ✔️ Expected Behavior

how can i deal with it ?

### ❌ Actual Behavior

tell me , how to do it

**Comment by crazywoola** [comment]
We have fixed this issue in the main branch.

**Comment by qdaoming** [comment]
@crazywoola i tried in latest version. the error still exists.
which commit solved it?
