### ISSUE TITLE
The Qwen2-72B-Instruct model tool calling error

### ISSUE THREAD

**Issue by YvanCheng** [langgenius/dify#6793]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.6.15

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

I deployed Dify through Docker and deployed the Qwen2-72B-Struct and GLM-4 models. When using the Agent function, I found that GLM-4 could call Tools normally, but Qwen2 always prompted 400, The error message is as follows:

[openai_api_compatible] Error: API request failed with status code 400: {"object":"error","message":"[{'type': 'value_error', 'loc': ('body',), 'msg': 'Value error, Currently only named tools are supported.', 'input': {'model': 'Qwen2', 'stream': True, 'messages': [{'role': 'system', 'content': '用户输入：\\n查询[具体地区]\\n的天气情况。'}, {'role': 'user', 'content': '你好'}], 'tool_choice': 'auto', 'tools': [{'type': 'function', 'function': {'name': 'GetCurrentWeather', 'description': 'Get temperature for a specific location', 'parameters': {'type': 'object', 'properties': {'location': {'type': 'string', 'description': 'The city and state to retrieve the weather for'}}, 'required': ['location']}}}], 'user': '9fa31c2a-db1c-406f-b4a3-e9be5b1dcf81'}, 'ctx': {'error': ValueError('**Currently only named tools are supported**.')}}]","type":"BadRequestError","param":null,"code":400}
![agent-error](https://github.com/user-attachments/assets/a7c69857-2e31-4b81-b443-5a925d96c3f5)

tools json as follows:

{
      "openapi": "3.1.0",
      "info": {
        "title": "Get weather data",
        "description": "Retrieves current weather data for a location.",
        "version": "v1.0.0"
      },
      "servers": [
        {
          "url": "https://wttr.in"
        }
      ],
      "paths": {
        "/{location}": {
          "get": {
            "description": "Get temperature for a specific location",
            "operationId": "GetCurrentWeather",
            "parameters": [
              {
                "name": "location",
                "in": "path",
                "description": "The city and state to retrieve the weather for",
                "required": true,
                "schema": {
                  "type": "string"
                }
              }
            ],
            "deprecated": false
          }
        }
      },
      "components": {
        "schemas": {}
      }
    }

At first, I knew that there was a problem with deploying the Qwen2, but Dify was able to call Qwen2 normally, but could not call Tools:
<img width="1370" alt="image" src="https://github.com/user-attachments/assets/b77b4a63-40a5-40d8-8ef2-b3f775a03cbd">

### ✔️ Expected Behavior

call  tools normally

### ❌ Actual Behavior

call tools error

**Comment by crazywoola** [comment]
Already fixed in this PR https://github.com/langgenius/dify/pull/6719

**Comment by YvanCheng** [comment]
I don't think this is the same issue, and the error codes are also different. I upgraded to 0.6.16, but still receive the same issue.

**Comment by YvanCheng** [comment]
> Already fixed in this PR #6719

I don't think this is the same issue, and the error codes are also different. I upgraded to 0.6.16, but still receive the same issue.
