### ISSUE TITLE
Integrating Langsmith occurs an internal error

### ISSUE THREAD

**Issue by libukai** [langgenius/dify#7877]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.7.2

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

After creating a Langsmith project through testing code and verifying that the API KEY is correct. Then, an unsuccessful attempt was made to integrate langsmith in Dify's application, which resulted in an error.

### ❌ Actual Behavior

![image](https://github.com/user-attachments/assets/24b42c32-ef35-4051-a185-852871fbc035)

![CleanShot 2024-09-02 at 09 56 24@2x](https://github.com/user-attachments/assets/86766b27-7a2a-4b4c-b226-a4b2d2a33fca)

**Comment by crazywoola** [comment]
Already fixed in https://github.com/langgenius/dify/pull/7684

**Comment by libukai** [comment]
And the integration of Langfuse is also unsuccessful. 

When submit the configuration, the following error occurred:

```
1 validation error for LangfuseConfig project_key Field required [type=missing, input_value={'public_key': 'pk-lf-3e1.../us.cloud.langfuse.com'}, input_type=dict] For further information visit https://errors.pydantic.dev/2.8/v/missing
```

**Comment by crazywoola** [comment]
> And the integration of Langfuse is also unsuccessful.
> 
> When submit the configuration, the following error occurred:
> 
> ```
> 1 validation error for LangfuseConfig project_key Field required [type=missing, input_value={'public_key': 'pk-lf-3e1.../us.cloud.langfuse.com'}, input_type=dict] For further information visit https://errors.pydantic.dev/2.8/v/missing
> ```

This is fixed as well.

**Comment by iray1991** [comment]
@crazywoola still shows internal serval err for langsmith using 0.7.3

![image](https://github.com/user-attachments/assets/935f9c3f-a3fd-4104-90a0-f506a010cc80)
