### ISSUE TITLE
Workflow - Error

### ISSUE THREAD

**Issue by ip2cloud** [langgenius/dify#8229]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.0

### Cloud or Self Hosted

Self Hosted (Docker)

### Steps to reproduce

<img width="407" alt="image" src="https://github.com/user-attachments/assets/3f3fe28e-645b-4cea-83dc-39f80ab0f815">
Version 0.7.2 It's working correctly... when it goes through the classifier, it doesn't show anything other than what is instructed in the response node.

<img width="413" alt="image" src="https://github.com/user-attachments/assets/13f9009b-948c-4c6f-98d6-cc7c3274a024">
<img width="931" alt="image" src="https://github.com/user-attachments/assets/5e4b0333-5085-4a20-94b6-90638d58b11e">
Version 0.8.0
It is coming beyond what is instructed in the response node.

### ✔️ Expected Behavior

only see what is in the response node.

### ❌ Actual Behavior

what is coming in the classifier node, prior to the response node
<img width="402" alt="image" src="https://github.com/user-attachments/assets/70376b12-49b4-45b5-bc9f-846e7cd9adbb">
<img width="403" alt="image" src="https://github.com/user-attachments/assets/642ed789-40ad-45ed-b189-7904cc4f07b1">

**Comment by ip2cloud** [comment]
But if in the response node I only put output if only OK it should be just OK and not anything other than OK

**Comment by ip2cloud** [comment]
but it's like this... sir robot...

Still it's coming beyond ok

**Comment by ip2cloud** [comment]
<img width="1211" alt="Captura de Tela 2024-09-10 às 16 23 51" src="https://github.com/user-attachments/assets/33003907-da14-4e66-84f3-cb4feefc3f22">

**Comment by ip2cloud** [comment]
<img width="846" alt="image" src="https://github.com/user-attachments/assets/ddfaf5bb-6569-4086-8fd3-f8bdd1d82ea3">
with problems

<img width="1277" alt="image" src="https://github.com/user-attachments/assets/5eb56814-ec32-4d69-967a-a91c91b05084">

No problem! I discovered that when we place a response node after the classification node... it will always pick up more than just the responses.

**Comment by ip2cloud** [comment]
<img width="865" alt="Captura de Tela 2024-09-10 às 16 40 53" src="https://github.com/user-attachments/assets/4bcd6347-a1fe-40b3-9883-4750185df98a">
<img width="448" alt="Captura de Tela 2024-09-10 às 16 41 45" src="https://github.com/user-attachments/assets/b77afefb-c993-4a84-95f2-9a4fd44fafde">

**Comment by ip2cloud** [comment]
it is printing everything that enters the classifier... that is, it is not classifying

**Comment by crazywoola** [comment]
I think you can pull the v0.8.0 again and this should be resolved. We delete previous release but keep the same version number.

**Comment by ip2cloud** [comment]
I did the update and it still continues... It is processing the classifieds in parallel too...

**Comment by ip2cloud** [comment]
![Captura de Tela 2024-09-10 às 22 54 56](https://github.com/user-attachments/assets/160c71a6-6a92-45b3-b125-04b9d0d942c8)
![Captura de Tela 2024-09-10 às 22 56 57](https://github.com/user-attachments/assets/a49b792c-97e2-4a2f-a7a4-359091b0032c)

The blue wasn't supposed to come out, just the red.
The blue was just for the classifier to take the route.

**Comment by ip2cloud** [comment]
corrected in main langgenius/dify-web:main langgenius/dify-web:main
