### ISSUE TITLE
Knowledge base stays in queing mode, nothing happens

### ISSUE THREAD

**Issue by JanvanHout** [langgenius/dify#9050]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.8.3

### Cloud or Self Hosted

Cloud

### Steps to reproduce

Create New knowledge base and upload file (or files). File upload will segment and index will stay in Queue.

### ✔️ Expected Behavior

creating a working knowledge base, It should complete segmentation and indexing

### ❌ Actual Behavior

knowledgebase file segment and index stays in Queue. Dont't get completed, even with 'top-priority'

**Comment by JanvanHout** [comment]
Our issue is regarding the (payed) Cloud version of Dify....

**Comment by crazywoola** [comment]
Fixed.

**Comment by JanvanHout** [comment]
Hi,

Unfortunately it doesn't work. It isn't fixed?

Regards,


Jan van Hout



Van: crazywoola ***@***.***>
Verzonden: dinsdag 8 oktober 2024 02:48
Aan: langgenius/dify ***@***.***>
CC: Jan van Hout | Van Hout ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [langgenius/dify] Knowledge base stays in queing mode, nothing happens (Issue #9050)

U ontvangt niet vaak e-mail van ***@***.*** Ontdek waarom dit belangrijk is<https://aka.ms/LearnAboutSenderIdentification>

Fixed.

-
