### ISSUE TITLE
Knowledge Retrieval with external knowledge base

### ISSUE THREAD

**Issue by akkaz** [langgenius/dify#9142]
### Self Checks

- [X] This is only for bug report, if you would like to ask a question, please head to [Discussions](https://github.com/langgenius/dify/discussions/categories/general).
- [X] I have searched for existing issues [search for existing issues](https://github.com/langgenius/dify/issues), including closed ones.
- [X] I confirm that I am using English to submit this report (我已阅读并同意 [Language Policy](https://github.com/langgenius/dify/issues/1542)).
- [X] [FOR CHINESE USERS] 请务必使用英文提交 Issue，否则会被关闭。谢谢！:）
- [X] Please do not modify this template :) and fill in all the required fields.

### Dify version

0.9.1

### Cloud or Self Hosted

Cloud

### Steps to reproduce

I successfully connect an external knowledge base with the new feature provided in 0.9.1.

I can also test the knowledge base, in the dedicated section and it works fine.
![image](https://github.com/user-attachments/assets/449b0787-fa29-4829-9d0a-8574a83894af)

When you try to insert the "Knowledge Retrieval" in a workwflow, you get this error
![image](https://github.com/user-attachments/assets/92781cd4-b513-4419-90a2-81c77dc83283)

**Comment by Yawen-1010** [comment]
@akkaz This error may be caused by not successfully configuring the Rerank Model but turning on the switch. We are working on fixing this issue. This feature can still be used normally. You can choose to temporarily turn off the rerank model switch, or configure an available rerank model.

**Comment by BGFGB** [comment]
> @akkaz This error may be caused by not successfully configuring the Rerank Model but turning on the switch. We are working on fixing this issue. This feature can still be used normally. You can choose to temporarily turn off the rerank model switch, or configure an available rerank model.

In my case, the issue occurred because the knowledge retrieval returned an empty value, despite the status being a successful 200. Upon reviewing the code, I identified a potential problem here: https://github.com/langgenius/dify/blob/f4ce08211d3c614f6fbffb47d55e3a96678fb78d/api/core/workflow/nodes/knowledge_retrieval/knowledge_retrieval_node.py#L82. After commenting out that line, the issue was resolved.

Additionally, the documentation mentions that metadata should be a string (https://docs.dify.ai/zh-hans/guides/knowledge-base/external-knowledge-api-documentation), but in practice, the backend treats it as a dictionary (https://github.com/langgenius/dify/blob/3f1aa1f9e263f1134ba0a89c61a5b0dd14eac0ac/api/core/rag/models/document.py#L18). These inconsistencies didn't raise any errors during recall tests, but in actual workflows, they caused failures with empty data being returned.

After fixing these two points, everything is functioning correctly. However, regarding the first issue, simply commenting out that line might introduce other problems, so a more robust solution may be needed.

**Comment by Yawen-1010** [comment]
@JohnJyong

**Comment by sepa85** [comment]
For me also, enabling the rerank fixes the error, but always gives empty results.

**Comment by JohnJyong** [comment]
the cloud servcie has updated to the latest version ,pls try , thanks ~

**Comment by sepa85** [comment]
I still have empty result, even if knowledge test gives results. I'm using cloud.

![Screenshot_20241012-025710.jpg](https://github.com/user-attachments/assets/3e7991e9-f51a-4e84-992d-9bd34b743a76)

![Screenshot_20241012-025747.jpg](https://github.com/user-attachments/assets/b36d732f-084a-4cdf-8843-bb92d0c6d099)

**Comment by BGFGB** [comment]
> the cloud servcie has updated to the latest version ,pls try , thanks ~

"I see that your fix has been merged into the main branch, but the cloud service is using Version 0.9.1-fix1, and it seems that the fix hasn't been integrated yet."

**Comment by BGFGB** [comment]
@JohnJyong I locally merged your fix branch into version 0.9.1, and so far the issue appears to be resolved. Thank you for the fix!

**Comment by sepa85** [comment]
After updating to version 0.9.2, I'm still encountering issues with the workflow.

Now, whenever I click "Run," I receive a "Rerank model is required" error, regardless of whether rerank is enabled or disabled.

![Screenshot_20241014-231235.jpg](https://github.com/user-attachments/assets/f2330fcc-1597-4f05-85c8-5fb2fb425580)

![Screenshot_20241014-231240.jpg](https://github.com/user-attachments/assets/5a86cedd-6ec1-41c2-9aaa-dcd19e8d532d)

**Comment by YIXIAO0** [comment]
Hello, thank you for bringing this issue to our attention. After reviewing it, it seems to be a frontend saving bug. For now, please try returning to the studio and then selecting the app. This should prevent the 'rerank model is required' issue from appearing. We'll address this bug in the next release. Thank you for your patience!

**Comment by okarin1511** [comment]
Hey, i am also facing the same issue, the result in the chatflow is always empty, using Dify v0.12.1
